### PR TITLE
Fix pipeline spelling error

### PR DESCRIPTION
**Pull request by benfarr**
pipline -> pipeline

*Description of changes: Changed 'pipline' to 'pipeline'*

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Comment by ferdingler** [comment]
Hi @benfarr , thanks for your contribution! Do you mind please making the pull request against the `dev` branch instead of `master`?

**Comment by benfarr** [comment]
> Hi @benfarr , thanks for your contribution! Do you mind please making the pull request against the `dev` branch instead of `master`?

No problem, @ferdingler. Change made.

**Comment by ferdingler** [comment]
Hi @benfarr, it looks like your pull request now has 13 files changed and 10 commits. I assume this is because your fork is not up to date with the main repository. My suggestion would be to refresh your fork: 

From your local repository: 
```
git add remote upstream https://github.com/aws-samples/aws-serverless-cicd-workshop.git
git fetch upstream
```

Then refresh your local dev branch: 
```
git checkout dev
git rebase upstream/dev
```

Finally, looks like you have your changes in a `patch-1` branch. So you can do this: 
```
git checkout patch-1
git rebase dev
```

And git push to your fork: 
```
git push origin +patch-1
```

**Comment by ferdingler** [comment]
Alternatively, delete your current fork and create a new one. Apply your changes (since they are small) and create this pull request again. Sorry for all this hassle, but I cannot merge it the way it is because it would override existing commits.

**Comment by benfarr** [comment]
@ferdingler closing this PR and creating new.

**Pull request closed without merging**
